[toolchain]
package_manager = "yarn"

[features]
resolution = true
skip-lint = false

[programs.localnet]
stake = "Cu1Ty3HxTkKsrsLZfCy46BXtGUke7gjyYX6FhrQEWUr9"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "https://devnet.helius-rpc.com/?api-key=aa6ee31d-c1b7-4e26-9e55-4eb41cbe07cb"
wallet = "~/.config/solana/id.json"


[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
